name: things
description: Tiny Things Mobile App

version: 1.0.0

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1

  provider: ^4.3.2+2

  http: ^0.12.2
  http_parser: ^3.1.4
  crypto: ^2.1.5
  jwt_decode: ^0.1.0

  pref_dessert: ^0.5.1
  shared_preferences: ^0.5.12+2
  
  simple_animations: ^2.2.3
  page_transition: ^1.1.7+2

  animated_dialog: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  # ios: true
  android: true
  # image_path_ios: "assets/launcher/icon.png"
  image_path: "assets/check.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - ./assets/
   - ./assets/img/
